### ISSUE TITLE
Encountering "ModuleNotFoundError" error when running bdrmapit on terminal

### ISSUE THREAD

**Issue by isacmlee** [alexmarder/bdrmapit#21]
When I installed bdrmapit using "pip install -U traceutils ip2as" and then "pip install -U dbrmapit" in a fresh environment (using 'conda create -n bdrmapit python=3.7), I receive this message. I also had to pip install pb-amarder first bc there was a ModuleNotFoundError prior to this one. But this one I can't figure out how to solve.  
~~~
Traceback (most recent call last):
  File "/Users/isaclee/opt/anaconda3/envs/bdrmapit2/bin/bdrmapit", line 5, in <module>
    from scripts.bdrmapit import main
  File "/Users/isaclee/opt/anaconda3/envs/bdrmapit2/lib/python3.7/site-packages/scripts/bdrmapit.py", line 15, in <module>
    from bdrmapit.container.container import Container
  File "/Users/isaclee/opt/anaconda3/envs/bdrmapit2/lib/python3.7/site-packages/bdrmapit/container/container.py", line 11, in <module>
    from scripts.traceparser import ParseResults
  File "/Users/isaclee/opt/anaconda3/envs/bdrmapit2/lib/python3.7/site-packages/scripts/traceparser.py", line 15, in <module>
    from traceutils.scamper.pyatlas import AtlasReader as AtlasOddReader
ModuleNotFoundError: No module named 'traceutils.scamper.pyatlas'
~~~

**Comment by alexmarder** [comment]
Seems like the file was missing. Can you run `pip install -U traceutils` and see if it works?

**Comment by isacmlee** [comment]
It says that I have "Successfully installed traceutils-7.0.6". But I still encounter the same error message.

**Comment by alexmarder** [comment]
Yep. Fixed the mistake. It should at least import now. I don't often run bdrmapIT on Atlas so if you run into problems let me know.
